# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/sphinx directory
sphinx:
  configuration: docs/sphinx/conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub

# Python configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build configuration
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_install:
      # Install git for setuptools-scm to detect version
      - git fetch --unshallow || true
    post_build:
      - echo "Documentation built successfully!"
      - echo "Version:"
      - python -c "import persian; print(persian.__version__)"
